{% set version = "1.4.1" %}

package:
    name: tomopy
    version: {{ version }}

source:
    url: https://github.com/tomopy/tomopy/archive/{{ version }}.tar.gz
    fn: tomopy-{{ version }}.tar.gz
    sha256: e98cc5e9b075d5001a6bbdd42017180bd276a0f020800270dea936ae5422edd1

build:
  number: 0
  skip: true  # [win and py2k]
  script:
    - set CC=gcc  # [win]
    - mkdir -p $BUILD_PREFIX/include  # [unix]
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  ignore_run_exports:
    - blas

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - make  # [win]
  host:
    - pip
    - python
    - mkl-devel
    - setuptools
  run:
    - dxchange
    - futures  # [py2k]
    - mkl
    - mkl_fft
    - numexpr
    - numpy
    - pywavelets
    - python
    - scikit-image
    - scipy
    - six
    - tifffile

test:
  requires:
    - nose
  imports:
    - tomopy
    - tomopy.misc
    - tomopy.prep
    - tomopy.recon
    - tomopy.sim
    - tomopy.util
  source_files:
    - test/*
  commands:
    - nosetests test

app:
    own_environment: True

about:
    home: http://tomopy.readthedocs.io
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: 'Tomographic reconstruction in Python.'
    description: |
      TomoPy is an open-source Python package for tomographic data processing
      and image reconstruction.
    doc_url: http://tomopy.readthedocs.io
    dev_url: https://github.com/tomopy/tomopy

extra:
    recipe-maintainers:
        - dgursoy
        - decarlof
        - licode
        - ravescovi
        - tacaswell
        - oleksandr-pavlyk
        - carterbox
