travis:
  secure:
    BINSTAR_TOKEN: lBtlgtslkcnUYmKCUstokW5qjzIBULwN3snNHYPbTj+DhxQLXgrV1opccfD+Uz5x6PHCSNrPEQmvoxcakF2zYpKA1hzBVC+Vctwt2XlmRf+UpwVs3sNkf4I5LIhKcqHSuZib5pdhYMYzqln8Rh5RBD9pFcVuz95OwiGpjkcVsQ5jVOgKp85ZowdBCdW49GwnzYyxw9i4BIEZSgCLXORYyJMi4TzokigZ0KBfzGL5V2Gc3Nasxl2acWmjdUthY0WSkr6b9I3ARasgvZk49dqdqlgV76Yvq/dxxtZr3rssJpveGje7NTn7PQSSwDvxTEUKYJNiRWjwJgnHVExkrDXD7MSgMFsZ+v79XRq3Axw8OLNpX4lwH57pSaIw5A8vc00FbJRIbuAoOO7loxlJ7rZkwAodZ95ped4qYlmDiAblX89Nl4g+YdhIBWZu3sx3qPmqFAxNlVJG5hO/Lms5Ow7suEF23Cj7JMfsQ7NFCH85FKHeCIsvfOHK/8NhDYYmb8CWEezYO++W7wMbD+qY8gdflq7X61A9r2kL/ZRZFsSs9I3I9F+0SQQsdegQnBYYyup/q450GMm1NwYilXycLgOGmfPqsmE8GtfTkMxcKQy8EzgdtoUGh9xC5ODl25RduS7jfPq6G4t5NyXlouEF8hCUvayFxIEQ5LvHLVGBh8CE6AM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
