travis:
  secure:
    BINSTAR_TOKEN: CEeMWZUEjsK2zJ7yII1k4PBJyUDxWU7YVRHCZIXzteSPSEgiXXlxeJ9D+q8D4uJh4YYTGeNp2mzDsMo60mOkm5SjjrX27mHmJauDc66hwNd5Nf4fFtA2xdQ3sT7hqaOvBTNpqAmx6UDvI/60jDIStfIXAmM/8Iihtcq6A9+QmbZcRayYnF8Kc0uis+pC/V9PJ8CGvi5+1S4CykDZJ1f0p9znEnxdrbiYwTyQpt6pe2wOxBRxSEy9VvqouwbVv3gCHKWbozduROhxcA3HdR4Zr8JU1k0/x8ITqmum3NRBdvktf9t1x/guRNote3p+ERaiQqF081oNkfq6/LwZRRSiE4fVxjwGrJXqc1AKy63rnbf29rksvDUIOckobLcwztN+QlJkH9A56tVB+uP47v+a8bpIeg090ZrPgad++FZq2fZlotr01/17xdfJwPEJln/tZzkt3qkOeqyoB13J5BIpkjbh3Wy6KgupnJHLjtG1lS6yQ1SXsUF0+JEeEYH8QhV4fRJLJ40T0LJ2kPELwa25RwqPZCEoE9NKNgsD/NuGHLa8rI78e/09SmTb+YDNSv+9q7RJq9tLVg/SUfAVCb5rKADcaU1rM0Is4XZW9rF1lYRrZTbKgHpy7z+KjNUDY7mMtyXIFuqRp0NA4rJ9UOmmII3xLH8603UqVAY3TRkm8Hk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
