travis:
  secure:
    BINSTAR_TOKEN: QOhHvL5iP910db4vJsdkGB+5w+3asAAh1KOisz+HnlyEgiGBOK05HNMp82rEsPKjCAjd3ZqNhvnFw2lmFf/+CFPvrUMnjSMHfPfZvEvkXlhg7iVIMzX6tikOMp1Hn1bGRPTxIZQ7NP9jjafRm9XOqZADy9HawnCKegOWaIbaWGBIhN0AhOv9hbwAb1PgjeCsz9ay4uSsMYkcSK6pDUEBkuslIvACpG88knwjRW0kqFoMTaL/GJcCPgweIuwK31pD56x8XMicrnrdBIQ35ccgR5WZ8e2EOLuCZLT6mRJHo4o3OuRuyVtOQy/Y87hAmUraEfpCEH9weF2xcaNTtWWOozU1BEA+ZoTme0kVZtpcdCJPfvT7Wyn86gx+r9K/mGo88vBDtRYxEaIOyWKpcHqHrnE4JpWgZCJu73KBJMvUKM34SUejOeZq7YKRghWG7J9LwYA8FfmCp475yzVju/NCkaqdtcdMcyzKRmeXjv8jOFXmhr6BiP7eXT/21V8HzdcUB0iVJi+PZLi5xkS4ZWWs4BdFXgoh1Byf0CeZsaDKSOw9FxfcoE9q+l50CuEbB/z+c9Du1DE4oVTYUIWN9QfDWysvVA2ZYfqWACvDDErDiTKLGdU/z1j7W+cZsiEt7w8o01Izmsx6e6mHaSO4RWbp1V+Y51LSK5/GBBRuZnh8CNY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
